version: "3.8"

services:
  # 1. DATABASE (Bản nhẹ cho AWS 1GB RAM)
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: hr-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MatKhauManh123!"
    ports:
      - "1434:1433" # Mở cổng 1434 để bạn có thể dùng SSMS từ nhà soi vào DB trên AWS
    volumes:
      - sql_data:/var/opt/mssql
      - ./HRApi.bak:/var/opt/mssql/HRApi.bak
    restart: always

  # 2. BACKEND API
  backend:
    build:
      context: ./HRApi/HRApi
      dockerfile: Dockerfile
    container_name: hr-backend
    ports:
      - "5260:8080" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./HRApi/HRApi/wwwroot:/app/wwwroot
      - ./HRApi/EmailTemplates:/app/EmailTemplates
    depends_on:
      - sqlserver
    restart: on-failure

  # 3. FRONTEND
  frontend:
    build:
      context: ./hr-staffflow
      dockerfile: Dockerfile
    container_name: hr-staffflow
    ports:
      - "80:80" # Map ra cổng 80 để vào web không cần gõ :3000
    depends_on:
      - backend

volumes:
  sql_data: