version: "3.8"

services:
  # 1. DATABASE
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: hr-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MatKhauManh123!"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./HRApi.bak:/var/opt/mssql/HRApi.bak
    restart: always

  # 2. BACKEND API
  backend:
    build:
      context: ./HRApi/HRApi
      dockerfile: Dockerfile
    container_name: hr-backend
    ports:
      - "5260:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=THIS_IS_A_DEV_SECRET_CHANGE_ME_TO_LONG_RANDOM_BUT_NOW_IN_ENV
      - Smtp__Pass=htmvviguqmiejkwe
    volumes:
      - ./HRApi/HRApi/wwwroot:/app/wwwroot
      - ./HRApi/EmailTemplates:/app/EmailTemplates
    depends_on:
      - sqlserver
    restart: on-failure

  # 3. FRONTEND (Đã khớp chuẩn cổng 443:443 theo lời admin)
  frontend:
    build:
      context: ./hr-staffflow
      dockerfile: Dockerfile
    container_name: hr-staffflow
    ports:
      - "443:80" 
    depends_on:
      - backend
    restart: always

volumes:
  sql_data: