// <auto-generated />
using System;
using HRApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818031537_MigrationMoi")]
    partial class MigrationMoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRApi.Models.ChucVuNhanVien", b =>
                {
                    b.Property<string>("MaChucVuNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("HSPC")
                        .HasColumnType("float");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVuNV");

                    b.ToTable("ChucVuNhanViens");
                });

            modelBuilder.Entity("HRApi.Models.ChuyenNganh", b =>
                {
                    b.Property<string>("MaChuyenNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChuyenNganh");

                    b.ToTable("ChuyenNganhs");
                });

            modelBuilder.Entity("HRApi.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiTamTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChucVuNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaChuyenNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTrinhDoHocVan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapCCCD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCapCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoanNH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangHonNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("sdt_NhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVuNV");

                    b.HasIndex("MaChuyenNganh");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTrinhDoHocVan");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt_PhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("HRApi.Models.TrinhDoHocVan", b =>
                {
                    b.Property<string>("MaTrinhDoHocVan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("HeSoBac")
                        .HasColumnType("float");

                    b.Property<string>("TenTrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrinhDoHocVan");

                    b.ToTable("TrinhDoHocVans");
                });

            modelBuilder.Entity("HRApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRApi.Models.HopDong", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.HasOne("HRApi.Models.ChucVuNhanVien", "ChucVuNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVuNV");

                    b.HasOne("HRApi.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChuyenNganh");

                    b.HasOne("HRApi.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.HasOne("HRApi.Models.TrinhDoHocVan", "TrinhDoHocVan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTrinhDoHocVan");

                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("ChuyenNganh");

                    b.Navigation("PhongBan");

                    b.Navigation("TrinhDoHocVan");
                });

            modelBuilder.Entity("HRApi.Models.ChucVuNhanVien", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.ChuyenNganh", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("HRApi.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.TrinhDoHocVan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
