// <auto-generated />
using System;
using HRApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305085518_AddColumnChuKy")]
    partial class AddColumnChuKy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRApi.Models.ActiveQRToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActiveQRTokens");
                });

            modelBuilder.Entity("HRApi.Models.BangLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaChot")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KhauTruBHTN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KhauTruBHXH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KhauTruBHYT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KhoanTruKhac")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongChinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongDongBaoHiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongOT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTinhLuong")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("ThucLanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThueTNCN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TongGioOT")
                        .HasColumnType("float");

                    b.Property<double>("TongNgayCong")
                        .HasColumnType("float");

                    b.Property<decimal>("TongPhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThuNhap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("BangLuongs");
                });

            modelBuilder.Entity("HRApi.Models.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DiMuon")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GioCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GioCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiNgayCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<double>("NgayCong")
                        .HasColumnType("float");

                    b.Property<double>("SoGioLamViec")
                        .HasColumnType("float");

                    b.Property<double>("SoGioOT")
                        .HasColumnType("float");

                    b.Property<bool>("VeSom")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("HRApi.Models.ChucVuNhanVien", b =>
                {
                    b.Property<string>("MaChucVuNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("HSPC")
                        .HasColumnType("float");

                    b.Property<string>("MoTaCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVuNV");

                    b.HasIndex("RoleId");

                    b.ToTable("ChucVuNhanViens");
                });

            modelBuilder.Entity("HRApi.Models.ChuyenNganh", b =>
                {
                    b.Property<string>("MaChuyenNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChuyenNganh");

                    b.ToTable("ChuyenNganhs");
                });

            modelBuilder.Entity("HRApi.Models.DangKyCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KinhPhiDuKien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("LyDoTamUng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MucDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGuiDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCongTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongTien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienTamUng")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DangKyCongTacs");
                });

            modelBuilder.Entity("HRApi.Models.DangKyOT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGuiDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLamThem")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoGio")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DangKyOTs");
                });

            modelBuilder.Entity("HRApi.Models.DonNghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGuiDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoNgayNghi")
                        .HasColumnType("float");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonNghiPheps");
                });

            modelBuilder.Entity("HRApi.Models.FaceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceDescriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("FaceDatas");
                });

            modelBuilder.Entity("HRApi.Models.HopDong", b =>
                {
                    b.Property<string>("SoHopDong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LuongDongBaoHiem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoHopDong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("HRApi.Models.KhoaCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KhoaCongs");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuKy")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ChuyenNganhChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiTamTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HeDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("LuongTroCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaChucVuNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaChuyenNganh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaQuanLyTrucTiep")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTrinhDoHocVan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapCCCD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapHoChieu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanCCCD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanHoChieu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiLienHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCapCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCapHoChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDKKCB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuongXaThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyenThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocGiaThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SdtKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBHXH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoBHYT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHoChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoanNH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoanNH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhThanhThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangHonNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("sdt_NhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVuNV");

                    b.HasIndex("MaChuyenNganh");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaQuanLyTrucTiep");

                    b.HasIndex("MaTrinhDoHocVan");

                    b.HasIndex("RoleId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("sdt_PhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("HRApi.Models.TrinhDoHocVan", b =>
                {
                    b.Property<string>("MaTrinhDoHocVan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("HeSoBac")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTrinhDoHocVan");

                    b.ToTable("TrinhDoHocVans");
                });

            modelBuilder.Entity("HRApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRApi.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HRApi.Models.BangLuong", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.ChamCong", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.ChucVuNhanVien", b =>
                {
                    b.HasOne("HRApi.Models.UserRole", "UserRole")
                        .WithMany("ChucVuNhanViens")
                        .HasForeignKey("RoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("HRApi.Models.DangKyCongTac", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.DangKyOT", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.DonNghiPhep", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.FaceData", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.HopDong", b =>
                {
                    b.HasOne("HRApi.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.HasOne("HRApi.Models.ChucVuNhanVien", "ChucVuNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVuNV");

                    b.HasOne("HRApi.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChuyenNganh");

                    b.HasOne("HRApi.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.HasOne("HRApi.Models.NhanVien", "QuanLyTrucTiep")
                        .WithMany()
                        .HasForeignKey("MaQuanLyTrucTiep");

                    b.HasOne("HRApi.Models.TrinhDoHocVan", "TrinhDoHocVan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTrinhDoHocVan");

                    b.HasOne("HRApi.Models.UserRole", "UserRole")
                        .WithMany("NhanViens")
                        .HasForeignKey("RoleId");

                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("ChuyenNganh");

                    b.Navigation("PhongBan");

                    b.Navigation("QuanLyTrucTiep");

                    b.Navigation("TrinhDoHocVan");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("HRApi.Models.ChucVuNhanVien", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.ChuyenNganh", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.NhanVien", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("HRApi.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.TrinhDoHocVan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HRApi.Models.UserRole", b =>
                {
                    b.Navigation("ChucVuNhanViens");

                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
